### ISSUE TITLE
Regarding pretrained checkpoints

### ISSUE THREAD

**Issue by mnmjh1215** [samgregoost/atmg#2]
Hello,
It seems that the link for downloading pretrained ATMG checkpoints is incorrect, as it points to MERU checkpoints.

**Comment by samgregoost** [comment]
Thank you for pointing this out. We have updated it.

**Comment by mnmjh1215** [comment]
Thanks for the update!

I have a question regarding the learned curvature of the pretrained model.
When I loaded the ATMG vit-base and ATMG vit-small checkpoints, the value of the learned curvature is 0.1, while the Figure 13 of the supplemental shows that the learned curvature is 5.
Maybe the checkpoint is incorrect?
